# Generated by Django 5.2.1 on 2025-05-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/"),
        ),
    ]
