# Generated by Django 5.2.1 on 2025-05-11 22:48

from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model("recipes", "Category")
    default_categories = [
        ("Légères", "Des recettes peu caloriques pour garder la ligne."),
        ("Protéinées", "Riches en protéines, parfaites après le sport."),
        ("Réconfortantes", "Gras et chaleureux, parfaites en hiver."),
        ("Pressées", "Ultra rapides à préparer."),
        ("Fraîches", "Parfait pour les journées chaudes."),
        ("Étoilées", "Pour les grandes occasions."),
        ("Sucrées", "Desserts et petits plaisirs sucrés."),
    ]
    for name, description in default_categories:
        Category.objects.get_or_create(name=name, defaults={"description": description})


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_recipe_picture"),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
