# Generated by Django 5.2.1 on 2025-05-12 16:31

from django.db import migrations, models
from django.utils.text import slugify


def populate_slug_fields(apps, schema_editor):
    Category = apps.get_model("recipes", "Category")
    Recipe = apps.get_model("recipes", "Recipe")

    for category in Category.objects.all():
        category.slug = slugify(category.name)
        category.save()

    for recipe in Recipe.objects.all():
        recipe.slug = slugify(recipe.title)
        recipe.save()


class Migration(migrations.Migration):
    replaces = [
        ("recipes", "0003_category_slug_recipe_slug"),
        ("recipes", "0004_add_slug_fields"),
        ("recipes", "0005_add_unique_constraint_to_slugs"),
    ]

    dependencies = [
        ("recipes", "0002_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.RunPython(
            code=populate_slug_fields,
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
