# Generated by Django 5.2.1 on 2025-05-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='nutrition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='variations_improvements',
            field=models.TextField(blank=True),
        ),
    ]
