# Generated by Django 5.2.1 on 2025-05-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_nutrition_recipe_variations_improvements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='variations_improvements',
            new_name='variations',
        ),
    ]
